### ISSUE TITLE
MapeCalculator module

### ISSUE THREAD

**Issue by marianturowski** [KIT-IAI/pyWATTS#104]
**What is your feature request related to?**
* Module request

**Please describe the module/problem**
In addition to the RMSE and MAE, the MAPE is a common error measure.

**Describe the solution you'd like**
A MapeCalculator (similar to the already existing RmseCalculator and the MaeCalculator that is in preparation) would be beneficial.

**Additional context**
Please have a look at the existing RmseCalculator and the MaeCalculator that is in preparation because it could serve as a template.

**What type of Feature Request**
* Module request

**Comment by Kristof-K** [comment]
Due to division by 0, mape has to treat y zero values adequately. Current implementation calcs mape on all values with y != 0. If this is also done in the rolling variant, then the first error values aren't nan any more (incomplete windows are filled with nans) unlike the yet implemented error measures.

**Comment by benHeid** [comment]
You might first implement a non rolling variant. We have to discuss how to handle the mentioned issue. Possible solutions would be:
* fill with nans,
* ignore entries where the actual value is zero

**Comment by benHeid** [comment]
Now with the summary modules. It is sufficient if you only implement a mape summary. I think a rolling mape is currently not needed

**Comment by benHeid** [comment]
#139
