### ISSUE TITLE
Workday and Holiday not working in CalendarExtraction

### ISSUE THREAD

**Issue by jallmenroeder** [KIT-IAI/pyWATTS#243]
**Describe the bug**
The CalendarFeature.workday and CalendarFeature.holiday is not working in CalendarExtraction. 

**To Reproduce**
1. Go to examples/example.py
2. Replace CalendarFeature.weekday with CalendarFeature.workday or CalendarFeature.holiday in l.28
3. Run script

**Expected behavior**
The code runs without problems.

**Additional context**
[log.txt](https://github.com/KIT-IAI/pyWATTS/files/9150291/log.txt)

**Comment by benHeid** [comment]
Thank you for reporting the issue. I will investigate it in the next weeks. :)

**Comment by hertelm** [comment]
I can't reproduce the bug. Can you provide more information, such as the installed module versions (e.g. output of `pip freeze`)?
Do you have the latest version of the code, and did you make changes to it? According to the log you provided, the error is caused by a call of *is_workday(...)* in Line 133, but the line computing the *CalendarFeature.workday* feature is [Line 131](https://github.com/KIT-IAI/pyWATTS/blob/master/pywatts/modules/feature_extraction/calendar_extraction.py#L131) which calls *is_working_day(...)*.
